Add support for Rocky Linux, similar to the others
aws/efs-utils pull request #103
Opened 2021-07-21 23:16 UTC by NeilHanlon

*Issue #, if available:* N/A

*Description of changes:* 

Add Rocky Linux to `SKIP_NO_LIBWRAP_RELEASES` so instances running it can mount EFS.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-07-30 15:32 UTC, lisenet commented
Any ETA on when this can be merged?

2021-08-18 16:53 UTC, lukosbo commented
Thanks for the PR. We’ll have someone take a look.

2021-12-17 06:22 UTC, Cappuccinuo commented
Hey @NeilHanlon , thanks for the PR! Can you resolve the conflict based on current code base + combine the two commits into one commit? Thanks.

2021-12-18 18:37 UTC, NeilHanlon commented
> Hey @NeilHanlon , thanks for the PR! Can you resolve the conflict based on current code base + combine the two commits into one commit? Thanks.

Totally - forgot to squash at first but should be good now.

Thank you!

2021-12-20 06:17 UTC, Cappuccinuo approved these changes

2021-12-20 07:28 UTC, Cappuccinuo commented on src/mount_efs/__init__.py
> +ROCKY8_RELEASE_NAME = 'Rocky Linux release 8'
nit: Can you make this double quoted?

2021-12-20 07:33 UTC, Cappuccinuo requested changes
Minor format change. Single quote -> double quote

2021-12-21 01:24 UTC, Cappuccinuo approved these changes

2021-12-21 02:00 UTC, Cappuccinuo commented
Merged, let us know if you encounter any issue while using this distribution.

2021-12-21 02:00 UTC, merged