Disable journal entry fetch from systemctl call
aws/efs-utils pull request #148
Opened 2022-11-29 16:00 UTC by halfdime-code

systemctl has known performance issues with large numbers of journal files.

See https://github.com/systemd/systemd/issues/2460.

Adding --lines=0 argument to call improves call speed when systemctl is called for the first time. If this first call happens from mount.efs, this may result in high latency for the mount as it waits for all of the journal files to be indexed. Given that mount.efs is only looking for the exit code of the command and does not care about the journal entries, there is no loss of usability by adding the flag.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-29 16:03 UTC, halfdime-code commented
Test run on my mac is failing with the following output that seems related to a lack of stunnel.
[CI run passed](https://app.circleci.com/pipelines/github/halfdime-code/efs-utils/1/workflows/2e5e22fe-8395-4da1-96d7-c0f3d14c46e2) with no errors which is probably a better indicator.
```
Required test coverage of 80% reached. Total coverage: 83.78%
========================================================================================================================================== short test summary info ==========================================================================================================================================
FAILED test/mount_efs_test/test_get_init_system.py::test_get_init_system_from_file - AssertionError: assert 'systemd' == 'launchd'
FAILED test/mount_efs_test/test_get_init_system.py::test_get_init_system_nonexistent_file - AssertionError: assert 'unknown' == 'launchd'
FAILED test/mount_efs_test/test_get_nfs_mount_options.py::test_get_default_nfs_mount_options - AssertionError: assert 'nfsvers=4.1' in 'nfsvers=4.0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,mountport=2049'
FAILED test/mount_efs_test/test_main.py::test_main_no_tls - AssertionError: Expected mock to have been not called. Called 1 times.
FAILED test/mount_efs_test/test_main.py::test_main_port_without_tls - AssertionError: Expected mock to have been not called. Called 1 times.
FAILED test/mount_efs_test/test_mount_nfs.py::test_mount_nfs - AssertionError: assert '/sbin/mount.nfs4' == '/sbin/mount_nfs'
FAILED test/mount_efs_test/test_mount_nfs.py::test_mount_nfs_with_fallback_ip_address - AssertionError: assert '/sbin/mount.nfs4' == '/sbin/mount_nfs'
FAILED test/mount_efs_test/test_mount_nfs.py::test_mount_nfs_tls - AssertionError: assert '127.0.0.1' in '-o'
FAILED test/mount_efs_test/test_mount_nfs.py::test_mount_nfs_tls_netns - AssertionError: assert '/sbin/mount.nfs4' == '/sbin/mount_nfs'
FAILED test/mount_efs_test/test_mount_nfs.py::test_mount_tls_mountpoint_mounted_with_nfs - ValueError: not enough values to unpack (expected 2, got 0)
FAILED test/mount_efs_test/test_parse_arguments.py::test_parse_arguments_verbose - AttributeError: 'NoneType' object has no attribute 'has_section'
FAILED test/mount_efs_test/test_parse_arguments.py::test_parse_arguments - AttributeError: 'NoneType' object has no attribute 'has_section'
FAILED test/mount_efs_test/test_parse_arguments.py::test_parse_arguments_with_az_dns_name_mount_az_not_in_option - AssertionError: assert '/dir' == 'foo,bar=baz,quux'
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_file - AssertionError: assert {'fips': 'no'...USEADDR=yes']} == {'fips': 'no'...EUSEADDR=yes'}
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_file_with_az_as_dns_name - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_with_debug - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_with_debug_and_logs_file - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_hostname_supported_flag_not_set - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_hostname_supported_flag_set_false - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_hostname_supported_flag_set_true - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_hostname_not_supported_flag_not_specified - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_hostname_not_supported_flag_set_false - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_hostname_not_supported_flag_set_true - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_validity_supported_ocsp_enabled - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_validity_supported_ocsp_disabled - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_validity_not_supported_ocsp_disabled - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_check_cert_validity_not_supported_ocsp_enabled - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_with_verify_level - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_libwrap_not_supported - AssertionError: assert {'fips': 'no'...USEADDR=yes']} == {'fips': 'no'...EUSEADDR=yes'}
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_libwrap_supported - AssertionError: assert {'fips': 'no'...USEADDR=yes']} == {'fips': 'no'...EUSEADDR=yes'}
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_with_fall_back_ip_address - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_foreground_quiet_not_supported - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_foreground_quiet_supported - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_foreground_quiet_supported_debug_enabled - ValueError: list.remove(x): x not in list
FAILED test/mount_efs_test/test_write_stunnel_config_file.py::test_write_stunnel_config_fips_enabled - ValueError: list.remove(x): x not in list
FAILED test/watchdog_test/test_check_efs_mounts.py::test_no_mount_for_state_file - ValueError: substring not found
FAILED test/watchdog_test/test_check_efs_mounts.py::test_no_mount_for_state_file_mark_as_unmounted - ValueError: substring not found
FAILED test/watchdog_test/test_get_current_local_nfs_mounts.py::test_local_nfs_mount - assert 1 == 0
FAILED test/watchdog_test/test_get_current_local_nfs_mounts.py::test_local_nfs_mount_default_nfs_port - assert 1 == 0
FAILED test/watchdog_test/test_get_current_local_nfs_mounts.py::test_local_nfs_mount_noresvport - assert 1 == 0
=============================================================================================================================== 40 failed, 497 passed, 11 warnings in 22.96s ================================================================================================================================
make: *** [test] Error 1
```

2022-11-30 08:29 UTC, Cappuccinuo commented
Thanks for the finding.

Going through the `systemctl --help`, instead of using `systemctl status`, can we just use `systemctl is-active` given we only care about whether the target/service is active or not?

```python
import os
import subprocess

with open(os.devnull, "w") as devnull:
    rc = subprocess.call(
                ["systemctl", "is-active", "network.target"],
                stdout=devnull,
                stderr=devnull,
                close_fds=True,
            )

if rc != 0:
   print("Return code is non 0, assume network target is not active.")
else:
   print("Success, network target is active.")

```
I used the above script to test whether the return code can still be used, seems working

When network is on

```output
$ systemctl is-active network.target
active
$ systemctl status network.target
● network.target - Network
   Loaded: loaded (/usr/lib/systemd/system/network.target; static; vendor preset: disabled)
   Active: active since Wed 2022-11-30 08:07:51 UTC; 12min ago
     Docs: man:systemd.special(7)
           http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget

Nov 30 08:07:51 ip-**.ec2.internal systemd[1]: Reached target Network.
$ sudo python3 test-network.py
Success, network target is active.
```

When network is off

```output
$ sudo systemctl stop network.target
$ systemctl status network.target
● network.target - Network
   Loaded: loaded (/usr/lib/systemd/system/network.target; static; vendor preset: disabled)
   Active: inactive (dead) since Wed 2022-11-30 08:21:25 UTC; 4s ago
     Docs: man:systemd.special(7)
           http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget

Nov 30 08:07:51 ip-xx.ec2.internal systemd[1]: Reached target Network.
Nov 30 08:21:25 ip-xx.ec2.internal systemd[1]: Stopped target Network.
$ systemctl is-active network.target
inactive
$ sudo python3 test-network.py
Return code is non 0, assume network target is not active.
```

2022-11-30 17:42 UTC, halfdime-code commented
> Thanks for the finding.
> 
> Going through the `systemctl --help`, instead of using `systemctl status`, can we just use `systemctl is-active` given we only care about whether the target/service is active or not?

As far as I can tell, that works just fine as well and should still avoid the journal issues.

Do you want me to update this PR or just close it in lieu of another that you own?

2022-12-01 08:47 UTC, Cappuccinuo requested changes
Can you rebase the two commits into a single one? Also did you verified this change on your side?

2022-12-01 22:47 UTC, halfdime-code commented
> Can you rebase the two commits into a single one? 
Done.

> Also did you verified this change on your side?
Change was handed off to customer experiencing the issue for further testing in their environment that was impacted.

Other than the automated checks, what verification are you looking for?

`systemctl is-active network.target` will exit non-zero if the target is in any state other than active. The [exit status definitions](https://www.freedesktop.org/software/systemd/man/systemctl.html#Exit%20status) introduce in [this commit](https://github.com/systemd/systemd/commit/23a9ffb0935b6814c6b267fe22f94f1436bb7a5e) aren't super specific.

The difference from `status` to `is-active` seems sufficient as the status path is an implicit exit where as `is-active` is asking a specific question about the service. From `man 1 systemctl`:

> is-active PATTERN...
>   Check whether any of the specified units are active (i.e. running). Returns an exit code 0 if at least one is active,
>   or non-zero otherwise. Unless --quiet is specified, this will also print the current unit state to standard output.
> ...
> status [PATTERN...|PID...]]
>   Show terse runtime status information about one or more units, followed by most recent log data from the 
>   journal. If no units are specified, show system status. If combined with --all, also show the status of all units
>   (subject to limitations specified with -t). If a PID is passed, show information about the unit the process belongs to.
> 
>   This function is intended to generate human-readable output. If you are looking for computer-parsable
>   output, use show instead. By default this function only shows 10 lines of output and ellipsizes lines to fit in the
>   terminal window. This can be changes with --lines and --full, see above. In addition, journalctl --unit=NAME use
>   a similar filter for messages and might be more convenient.

2022-12-02 01:27 UTC, Cappuccinuo approved these changes

2022-12-02 01:28 UTC, merged