filename of .deb-package should include architecture
aws/efs-utils pull request #44
Opened 2020-02-24 12:25 UTC by PhilSwiss

The filename of a Debian-package (.deb) should/must include the supported architecture:
For more info see - https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html

*Change to small for an issue, IMHO.*

*Description of changes:*
in the buildscript for the debian-package (build-deb.sh) line 64 now includes the choosen
architecture, with which the package will be build, thats all.
For more info see - https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-04-07 18:34 UTC, lilferna commented
PhilSwiss: Thanks for the contribution. We’ll evaluate your submission and follow up here with a decision.

2020-09-09 21:18 UTC, Thalience commented
This change is obviously correct and could not be simpler. What possible "evaluation" could AWS be waiting on?

2020-09-09 21:39 UTC, Cappuccinuo commented
@PhilSwiss , this branch has conflict with the main branch, could you please fix that? Thanks.

2020-09-15 08:20 UTC, Cappuccinuo requested changes
LGTM.

Could you please combine the two commits into one commit? Thanks.

2020-09-16 16:13 UTC, PhilSwiss commented
merge both commits into one and rebased to the current master

2020-09-16 18:58 UTC, Cappuccinuo approved these changes

2020-09-16 19:30 UTC, kbasv approved these changes

2020-09-18 05:20 UTC, merged